# Generated by Django 4.1.5 on 2023-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myinventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=300),
        ),
    ]
